baseURL = 'https://pawsey-internships.github.io/version-control/'
languageCode = 'en-us'
title = 'Pawsey Intern Training: Version Control'
theme = "learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "pawsey"
disableLandingPageButton = true
